predictor:
  name: bimodal
  version: 1.0
  CBP_ver: 2.0

parameters:
  CTR_WIDTH:
    type: 'int'
    min: 2
    max: 8
    val: 2
  CTR_INIT:
    type: 'int'
    min: 0
    max: 3
    val: 2
  PHT_SIZE:
    type: 'int'
    min: 6
    max: 22
    val: 6
  HYST:
    type: 'int'
    min: 1
    max: 4
    val: 1

